-- MySQL Script generated by MySQL Workbench
-- Fri Aug 30 09:27:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pacientes` (
  `idpacientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nascimento` DATE NOT NULL,
  `endereço` VARCHAR(45) NULL,
  `telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`idpacientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudante` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ingressado` DATE NOT NULL,
  `turma` INT NOT NULL,
  `Id_Medico` INT NOT NULL,
  PRIMARY KEY (`matricula`, `turma`, `Id_Medico`),
  INDEX `ID_medico_idx` (`Id_Medico` ASC) VISIBLE,
  CONSTRAINT `ID_medico`
    FOREIGN KEY (`Id_Medico`)
    REFERENCES `mydb`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `idmedico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `salario` DECIMAL NOT NULL,
  `id_paciente` INT NOT NULL,
  `estudante` INT NOT NULL,
  `consultas` INT NOT NULL,
  PRIMARY KEY (`idmedico`, `id_paciente`, `estudante`, `consultas`),
  INDEX `ID_paciente_idx` (`id_paciente` ASC) VISIBLE,
  INDEX `matricula_estudante_idx` (`estudante` ASC) VISIBLE,
  INDEX `id_consulta_idx` (`consultas` ASC) VISIBLE,
  CONSTRAINT `ID_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `mydb`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `matricula_estudante`
    FOREIGN KEY (`estudante`)
    REFERENCES `mydb`.`estudante` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_consulta`
    FOREIGN KEY (`consultas`)
    REFERENCES `mydb`.`consultas` (`idConsultas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consultas` (
  `idConsultas` INT NOT NULL AUTO_INCREMENT,
  `idpaciente` INT NOT NULL,
  `id_medico` INT NOT NULL,
  `data` DATETIME(10) NULL,
  `sintomas` VARCHAR(45) NOT NULL,
  `diagnostico` VARCHAR(45) NOT NULL,
  `tratamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idConsultas`, `idpaciente`, `sintomas`, `id_medico`),
  INDEX `ID_medico_idx` (`id_medico` ASC) VISIBLE,
  CONSTRAINT `ID_paciente`
    FOREIGN KEY (`idpaciente`)
    REFERENCES `mydb`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_medico`
    FOREIGN KEY (`id_medico`)
    REFERENCES `mydb`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pesquisas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pesquisas` (
  `idpesquisas` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `data-inicio` DATE NOT NULL,
  `data-termino` DATE NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `medico_supervisor` INT NOT NULL,
  `estudante_assis` INT NOT NULL,
  PRIMARY KEY (`idpesquisas`, `medico_supervisor`, `estudante_assis`),
  INDEX `ID_medico_idx` (`medico_supervisor` ASC) VISIBLE,
  INDEX `ID_estudante_assis_idx` (`estudante_assis` ASC) VISIBLE,
  CONSTRAINT `ID_medico`
    FOREIGN KEY (`medico_supervisor`)
    REFERENCES `mydb`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_estudante_assis`
    FOREIGN KEY (`estudante_assis`)
    REFERENCES `mydb`.`estudante` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exames` (
  `idExames` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `data` DATE NOT NULL,
  `id_paciente` INT NOT NULL,
  PRIMARY KEY (`idExames`, `id_paciente`),
  INDEX `ID_paciente_idx` (`id_paciente` ASC) VISIBLE,
  CONSTRAINT `ID_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `mydb`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requi_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requi_medico` (
  `idrequi_medico` INT NOT NULL AUTO_INCREMENT,
  `id_medico` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  `requi_medicocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idrequi_medico`, `id_medico`, `id_paciente`),
  INDEX `ID_medico_idx` (`id_medico` ASC) VISIBLE,
  INDEX `ID_paciente_idx` (`id_paciente` ASC) VISIBLE,
  CONSTRAINT `ID_medico`
    FOREIGN KEY (`id_medico`)
    REFERENCES `mydb`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `mydb`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resultados` (
  `id_requerimento` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  `id_medico` INT NOT NULL,
  PRIMARY KEY (`id_requerimento`, `id_paciente`, `id_medico`),
  INDEX `id_paciente_idx` (`id_paciente` ASC) VISIBLE,
  INDEX `id_medico_idx` (`id_medico` ASC) VISIBLE,
  CONSTRAINT `id_requerimento`
    FOREIGN KEY (`id_requerimento`)
    REFERENCES `mydb`.`requi_medico` (`idrequi_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `mydb`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_medico`
    FOREIGN KEY (`id_medico`)
    REFERENCES `mydb`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamentos` (
  `iddepartamentos` INT NOT NULL AUTO_INCREMENT,
  `id_mendico` INT NOT NULL,
  `id_pesquisas` INT NOT NULL,
  PRIMARY KEY (`iddepartamentos`, `id_mendico`, `id_pesquisas`),
  INDEX `id_medico_idx` (`id_mendico` ASC) VISIBLE,
  INDEX `id_pesquisas_idx` (`id_pesquisas` ASC) VISIBLE,
  CONSTRAINT `id_medico`
    FOREIGN KEY (`id_mendico`)
    REFERENCES `mydb`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_pesquisas`
    FOREIGN KEY (`id_pesquisas`)
    REFERENCES `mydb`.`pesquisas` (`idpesquisas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
