-- MySQL Script generated by MySQL Workbench
-- Tue Aug 27 21:59:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`morada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`morada` (
  `idmorada` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmorada`, `telefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Musico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Musico` (
  `idMusico` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `morada` VARCHAR(45) NULL,
  `telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`idMusico`, `morada`, `nome`),
  INDEX `ID_telefone_idx` (`telefone` ASC) VISIBLE,
  INDEX `ID_Morada_idx` (`morada` ASC) VISIBLE,
  CONSTRAINT `ID_Morada`
    FOREIGN KEY (`morada`)
    REFERENCES `mydb`.`morada` (`idmorada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_telefone`
    FOREIGN KEY (`telefone`)
    REFERENCES `mydb`.`morada` (`telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instrumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instrumento` (
  `idinstrumento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idinstrumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disco` (
  `iddisco` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `formato` VARCHAR(45) NOT NULL,
  `id_Musico` INT NOT NULL,
  PRIMARY KEY (`iddisco`, `titulo`, `id_Musico`),
  INDEX `id_Musico_idx` (`id_Musico` ASC) VISIBLE,
  CONSTRAINT `id_Musico`
    FOREIGN KEY (`id_Musico`)
    REFERENCES `mydb`.`Musico` (`idMusico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MUSICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MUSICA` (
  `titulo` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `disco_ID` INT NOT NULL,
  PRIMARY KEY (`titulo`, `autor`, `disco_ID`),
  INDEX `autor_musico_idx` (`autor` ASC) VISIBLE,
  INDEX `disco_ID_idx` (`disco_ID` ASC) VISIBLE,
  CONSTRAINT `autor_musico`
    FOREIGN KEY (`autor`)
    REFERENCES `mydb`.`Musico` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `disco_ID`
    FOREIGN KEY (`disco_ID`)
    REFERENCES `mydb`.`disco` (`iddisco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Musico_Musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Musico_Musica` (
  `musico_id` INT NOT NULL,
  `musica_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`musico_id`, `musica_id`),
  INDEX `musica_ID_idx` (`musica_id` ASC) VISIBLE,
  CONSTRAINT `musico_ID`
    FOREIGN KEY (`musico_id`)
    REFERENCES `mydb`.`Musico` (`idMusico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `musica_ID`
    FOREIGN KEY (`musica_id`)
    REFERENCES `mydb`.`MUSICA` (`titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Musico_instrumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Musico_instrumento` (
  `musico_id` INT NOT NULL,
  `instrumento_ID` INT NOT NULL,
  PRIMARY KEY (`musico_id`, `instrumento_ID`),
  INDEX `instrumento_ID_idx` (`instrumento_ID` ASC) VISIBLE,
  CONSTRAINT `musico_ID`
    FOREIGN KEY (`musico_id`)
    REFERENCES `mydb`.`Musico` (`idMusico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `instrumento_ID`
    FOREIGN KEY (`instrumento_ID`)
    REFERENCES `mydb`.`instrumento` (`idinstrumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
